### ISSUE TITLE
Help Installing HokuyoAist

### ISSUE THREAD

**Issue by Graziap89** [gbiggs/hokuyoaist#14]
Hello,
please, can you provides some instruction about the complete installation's process of flexiport and Hokuyoaist? i'm currently on ubuntu 16.04 LTS and i'm looking for some driver for Hokuyo URG-04LX-UG01 Scanning Laser Rangefinder . 

Thank you very much in advance for your help.

**Comment by gbiggs** [comment]
You need to build and install Flexiport, then build and install HokuyoAIST.

Flexiport:
```
mkdir build
cd build
cmake ..
make
make install
```

Do the same for HokuyoAIST.

If you want to change the install location, run `ccmake ..` before the `make` step and change the `INSTALL_PREFIX` value.
