### ISSUE TITLE
error -lbboost_python-mt

### ISSUE THREAD

**Issue by Graziap89** [gbiggs/hokuyoaist#15]
Hello, 
flexiport should be installed correctly after dependency resolution. Now I have an issue during the "make" process of installing hokuyoIAST: 

/usr/bin/ld: could not find -lbboost_python-mt

searching on internet I found that maybe the name of this lib is deprecated.
 Can you confirm it? if this is the problem where can we can modify the lib's name? Or is the problem another?

thank you very much.

**Comment by gbiggs** [comment]
I've fixed this in master. If you aren't using the Python bindings, you can also work around it by disabling them.
